server:
  port: 8087

mybatis:
  #  Mapper文件存放的位置
  mapperLocations: classpath:mapper/*.xml
  #  实体类所在的包
  typeAliasesPackage: com.fancky.shardingreadwrite.model.entity

# 配置 DataSource Driver


 # spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver
  # 指定 YAML 配置文件
  #spring.datasource.url=jdbc:shardingsphere:classpath:xxx.yaml
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingjdbc.yaml